In [2]:
import numpy as np

In [3]:
mA = np.array([[1, 2, 1], [-2, 1, 1]])
mB = np.array([[3, 1], [-1, 0], [2, 4]])
mC = np.array([[-2, 2], [1, -1], [1, 2]])

m1 = mA + 2 * mC.transpose()
m2 = mB + 2 * mC

print(m1)
print(m2)


[[-3  4  3]
 [ 2 -1  5]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [4]:
mZ = np.zeros((8, 8), dtype=np.int16)
mZ[::2, 1::2] = 1
mZ[1::2, ::2] = 1
print(mZ)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
v1 = np.arange(0, 1.5, 0.1)
v2 = np.arange(1, 7, 1)

v1 = np.reshape(v1, (5, 3))
v2 = np.reshape(v2, (3, 2))

print(v1)
print(v2)

vM = np.dot(v1, v2)

print(vM)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [6]:
v0 = np.arange(1, 72, 2, dtype=np.int32)
v1 = v0[v0 % 3 == 0]

print(v0)
print(v1)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
[ 3  9 15 21 27 33 39 45 51 57 63 69]
